# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install python3 pip and ansible latest
      - name: Install python and ansible
        run: sudo apt update && sudo apt install -y python3-pip && sudo pip3 install ansible
        
      # If `roles` folder exists, create a dummy.yml playbook to perform the syntax check
      - name: Creating dummy.yml from roles folder (if exists)
        run: test -d "roles" || exit 0 && echo $LINE1 > dummy.yml && echo $LINE2 >> dummy.yml && printf "  roles:\n" >> dummy.yml &&  for i in `ls roles`; do echo "  - $i" >> dummy.yml; done
        env: 
          LINE1: "---"
          LINE2: "- hosts: localhost"
          
      # Runs a set of commands using the runners shell
      - name: Ansible Syntax Check
        run: test -f "dummy.yml" && ansible-playbook $GITHUB_WORKSPACE/dummy.yml --syntax-check
      
      # If `roles` folder does not exist, assume we are in a repository containing just the role
      - name: Creating dummy2.yml from roles folder (if exists)
        run: export REPO=`echo $GITHUB_REPOSITORY | tr "/" "\n" | tail -1`; test -d "tasks" || exit 0 && echo $LINE1 > /tmp/dummy2.yml && echo $LINE2 >> /tmp/dummy2.yml && printf "  roles:\n" >> /tmp/dummy2.yml && printf "  - $REPO\n" >> /tmp/dummy2.yml
        env:
          LINE1: "---"
          LINE2: "- hosts: localhost"
        
        # Check ansible syntax
      - name: Ansible Syntax Check
        run: test -f "/tmp/dummy2.yml" || exit 0 &&  mkdir -p /tmp/roles/ && cd ..  && mv $REPO /tmp/roles/ && ANSIBLE_ROLES_PATH=/tmp/roles ansible-playbook /tmp/dummy2.yml --syntax-check
        
